# -*- coding: utf-8 -*-
"""part3_api_files

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HpenrD5ORWx3sB0vhe3vYP4Uz1gkjZU
"""

import requests

# this is the website link
url = "https://dummyjson.com/products"

# asking the website for data
response = requests.get(url)

# checking if request worked
print(response.status_code)

# converting data into python format
data = response.json()

print(data)

# task 1
# file reading and writing basic

# ---- PART A (writing) ----

# writing initial content
file = open("python_notes.txt", "w", encoding="utf-8")

file.write("Topic 1: Variables store data. Python is dynamically typed.\n")
file.write("Topic 2: Lists are ordered and mutable.\n")
file.write("Topic 3: Dictionaries store key-value pairs.\n")
file.write("Topic 4: Loops automate repetitive tasks.\n")
file.write("Topic 5: Exception handling prevents crashes.\n")

file.close()

print("file written successfully")


# appending more lines on the data
file = open("python_notes.txt", "a", encoding="utf-8")

file.write("Topic 6: Functions help reuse code.\n")
file.write("Topic 7: Python is easy to learn.\n")

file.close()

print("lines appended")


# ---- PART B (reading) ----

file = open("python_notes.txt", "r", encoding="utf-8")

lines = file.readlines()

file.close()

print("\nreading file:\n")

count = 0

for line in lines:
    count += 1
    print(str(count) + ". " + line.strip())


# total lines
print("\ntotal lines:", count)


# ---- searching keyword ----

keyword = input("\nenter keyword to search: ")

found = False

for line in lines:
    if keyword.lower() in line.lower():
        print(line.strip())
        found = True

if found == False:
    print("no matching lines found")

# task 2
# working with api (products)

import requests


# ---- step 1: trying to fetch products from api ----

url = "https://dummyjson.com/products?limit=20"

response = requests.get(url)

data = response.json()

products = data["products"]

print("ID | Title | Category | Price | Rating")

for p in products:
    print(p["id"], "|", p["title"], "|", p["category"], "|", p["price"], "|", p["rating"])


# ---- step 2: filter and sort ----

filtered = []

# filtering rating >= 4.5
for p in products:
    if p["rating"] >= 4.5:
        filtered.append(p)

# sorting by price (high to low)
filtered.sort(key=lambda x: x["price"], reverse=True)

print("\nfiltered products (rating >= 4.5):")

for p in filtered:
    print(p["title"], "-", p["price"], "-", p["rating"])


# ---- step 3: search by category ----

print("\nlaptops category:")

url2 = "https://dummyjson.com/products/category/laptops"

res2 = requests.get(url2)

data2 = res2.json()

for p in data2["products"]:
    print(p["title"], "-", p["price"])


# ---- step 4: post request to send the data out ----

print("\nposting new product...")

new_product = {
    "title": "My Custom Product",
    "price": 999,
    "category": "electronics",
    "description": "A product I created via API"
}

post_url = "https://dummyjson.com/products/add"

res_post = requests.post(post_url, json=new_product)

print("response from server:")
print(res_post.json())

# task 3
# exception handling part


# ---- Part A: safe divide ----

def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Error: Cannot divide by zero"
    except TypeError:
        return "Error: Invalid input types"


# testing
print(safe_divide(10, 2))
print(safe_divide(10, 0))
print(safe_divide("ten", 2))


# ---- Part B: file reader ----

def read_file_safe(filename):
    try:
        f = open(filename, "r", encoding="utf-8")
        data = f.read()
        f.close()
        return data
    except FileNotFoundError:
        print("Error: File '" + filename + "' not found.")
    finally:
        print("File operation attempt complete.")


# testing
print("\nreading correct file:")
print(read_file_safe("python_notes.txt"))

print("\nreading wrong file:")
print(read_file_safe("ghost_file.txt"))


# ---- Part C: api with error handling ----

import requests

url = "https://dummyjson.com/products?limit=5"

try:
    res = requests.get(url, timeout=5)
    data = res.json()
    print("\napi call success")
except requests.exceptions.ConnectionError:
    print("Connection failed. Please check your internet.")
except requests.exceptions.Timeout:
    print("Request timed out. Try again later.")
except Exception as e:
    print("Error:", e)


# POST request
try:
    post_url = "https://dummyjson.com/products/add"

    new_product = {
        "title": "Test Product",
        "price": 500
    }

    res_post = requests.post(post_url, json=new_product, timeout=5)
    print("\npost response:", res_post.json())

except requests.exceptions.ConnectionError:
    print("Connection failed. Please check your internet.")
except requests.exceptions.Timeout:
    print("Request timed out. Try again later.")
except Exception as e:
    print("Error:", e)


# ---- Part D: input loop ----

while True:
    user_input = input("\nEnter product ID (1-100) or 'quit': ")

    if user_input.lower() == "quit":
        break

    # checking if number
    if not user_input.isdigit():
        print("please enter a valid number")
        continue

    pid = int(user_input)

    if pid < 1 or pid > 100:
        print("id should be between 1 and 100")
        continue

    # making api call
    try:
        url = "https://dummyjson.com/products/" + str(pid)
        res = requests.get(url, timeout=5)

        if res.status_code == 404:
            print("Product not found.")
        elif res.status_code == 200:
            data = res.json()
            print(data["title"], "-", data["price"])

    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
    except Exception as e:
        print("Error:", e)

# task 4
# trying to log errors

from datetime import datetime
import requests


# function to write log
def write_log(msg):
    f = open("error_log.txt", "a")

    time_now = datetime.now()

    line = "[" + str(time_now) + "] " + msg + "\n"

    f.write(line)
    f.close()


# ---- 1. trigger connection error ----

try:
    bad_url = "https://this-host-does-not-exist-xyz.com/api"
    res = requests.get(bad_url, timeout=5)

except requests.exceptions.ConnectionError as e:
    print("connection error happened")
    write_log("ERROR in fetch_products: ConnectionError - " + str(e))


# ---- 2. trigger http error (404) ----

try:
    url = "https://dummyjson.com/products/999"
    res = requests.get(url, timeout=5)

    # checking status manually
    if res.status_code != 200:
        print("product not found")
        write_log("ERROR in lookup_product: HTTPError - 404 Not Found for product ID 999")

except Exception as e:
    write_log("ERROR: " + str(e))


# ---- read log file ----

print("\nerror log content:\n")

f = open("error_log.txt", "r")

data = f.read()
print(data)

f.close()